### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by minchopm** [angular-material-extensions/password-strength#104]
So when the component is switching between colors I am getting this one:
RegisterComponent.html:73 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'color: accent'. Current value: 'color: warn'.

Tested with Angular Material 7 and Angular 7

**Comment by AnthonyNahas** [comment]
this is a problem with the change detection operations (internal in angular). I will take a deeper look tonight. Thanks for reporting!

Tip: the message will be displayed only in debug mode. Try to add --prod and the message will disappear...

**Comment by AnthonyNahas** [comment]
fixed in [v3.3.0](https://github.com/angular-material-extensions/password-strength/releases)

Please consider to change the ChangeDetectionStrategy to OnPush for the parent component!
