### ISSUE TITLE
min input wont work properly

### ISSUE THREAD

**Issue by rubenCodeforges** [angular-material-extensions/password-strength#109]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
any

### Versions
any

### Repro steps

set `[min]="10" or  [min]="5"`

### The log given by the failure
due to this code https://github.com/angular-material-extensions/password-strength/blob/master/src/module/component/mat-password-strength/mat-password-strength.component.ts#L89 

the check will always perform check with hardcoded value

### Desired functionality
if you provide a `min` value the strength should consider the min value , currently it is not respecting and is using `8` always

### Mention any other details that might be useful
https://github.com/angular-material-extensions/password-strength/blob/master/src/module/component/mat-password-strength/mat-password-strength.component.ts#L89 this needs a change

**Comment by AnthonyNahas** [comment]
fixed + added for that an unit test - thanks for contributing - v3.3.1 is now out
