### ISSUE TITLE
As a developer, I want to be able to change the error language, so that user can understand the error message.

### ISSUE THREAD

**Issue by dgrafova** [angular-material-extensions/password-strength#111]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```
### Desired functionality
It would be great, if a developer could change the language of the error message or  just edit the error message text, according to the UI requirements.

**Comment by grantwhitaker06** [comment]
Just had to do this, made my own component, to accomplish it, and piped it to ngx-translate.

**Comment by AnthonyNahas** [comment]
I am looking forward to support multi languages, however I'm still waiting of the angular update which comes with the ivy renderer! Please take a look at this [thread](https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/76)! For the meanwhile, I am gonna implement maybe a workaround to achieve that ... like via data binding or similar...

**Comment by AnthonyNahas** [comment]
I have just released @angular-material-extensions/password-strength v3.4.0 which supports now custom messagesfor the info component as well as ngx-translate .. check the [demo app ](https://angular-material-extensions.github.io/password-strength/examples/mat-password-strength-info)

quick example with ngx-translate:

```html
<mat-password-strength-info
              [lowerCaseCriteriaMsg]="'LOWER_CASE_CRITERIA_MSG' | translate"
              [upperCaseCriteriaMsg]="'UPPER_CASE_CRITERIA_MSG '| translate"
              [digitsCriteriaMsg]="'DIGITS_CRITERIA_MSG '| translate"
              [specialCharsCriteriaMsg]="'SPECIAL_CHARS_CRITERIA_MSG' | translate"
              [minCharsCriteriaMsg]="'MIN_CHARS_CRITERIA_MSG' | translate"
              [passwordComponent]="passwordComponent">
</mat-password-strength-info>
```

enter anything you want --> 

```html
<mat-password-strength-info
              lowerCaseCriteriaMsg="your best lower case criteria msg"
              upperCaseCriteriaMsg="your best upper case criteria msg"
              digitsCriteriaMsg="your best digit char criteria msg"
              specialCharsCriteriaMsg="your best special char criteria msg"
              minCharsCriteriaMsg="your best min char criteria msg"
              [passwordComponent]="passwordComponent">
 </mat-password-strength-info>
```

cheers 🍻
