### ISSUE TITLE
Customizable Animations

### ISSUE THREAD

**Issue by SublimePotato** [angular-material-extensions/password-strength#131]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Desired functionality
Ability to disable and/or modify the animations on `<mat-password-strength-info>`.

### Mention any other details that might be useful
There aktually is a workaround which I used to disable the initial animation while keeping the others.
You can disable all animations on an element by setting `[@.disabled]="true"`. I simply check if the passwords `input` has focus and enable the animations only in this case -> 
`[@.disabled]="document.activeElement !== newPasswordInput"`

**Comment by AnthonyNahas** [comment]
I will take that in consideration in the next minor release

**Comment by AnthonyNahas** [comment]
@SublimePotato I can't find any solution for that... please consider reopening this ticket if you have any suggestions..
