### ISSUE TITLE
Missing flex library requirement in documention

### ISSUE THREAD

**Issue by matte00** [angular-material-extensions/password-strength#137]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10

### Versions

node v10.13.0
npm 6.4.1
Angular 7.2.1

### Description
Missing flex-library requirements in documentation. 
Without @angular/flex-layout library there are some alignment issues.

**Comment by AnthonyNahas** [comment]
you have right! I'm gonna add some flex css properties to be independent from the `@angular/flex-layout` library ;)

**Comment by AnthonyNahas** [comment]
I've just removed all flex layout's directives! If you're still having any troubles, please consider to reopen the issue!

[v.3.4.1](https://www.npmjs.com/package/@angular-material-extensions/password-strength) is now out
