### ISSUE TITLE
feat: add password confirmation (optional on demand)

### ISSUE THREAD

**Issue by AnthonyNahas** [angular-material-extensions/password-strength#143]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions
lib `v4.3.1`

### Desired functionality
developers should be able to add a form control ta validated the password confirmation

### Mention any other details that might be useful
#38

**Comment by andreElrico** [comment]
jep, wanted to write the same. We need password confirmation for this promising extention to be complete.

**Comment by AnthonyNahas** [comment]
added in [v3.8.0](https://www.npmjs.com/package/@angular-material-extensions/password-strength)
