### ISSUE TITLE
Force update strength meter

### ISSUE THREAD

**Issue by erikknaake** [angular-material-extensions/password-strength#149]
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

It would be nice if there was a way to force update the strength meter.

I have a scenario where the password is stored in a service, and the password-strength component is a part of a component that either has a load or a generate password component, when I come to the page with the generate component, a password is automatticly generated, but the strength bar is only updated when I update the password again. So either this is a bug where the strength meter misses an update, or it is a missing feature on how I can update the strength meter.

To be clear, when I change the password to the same password again it does not notice this too.

      <mat-password-strength class="strength" [password]="this.passwordUIHelper.password" (onStrengthChanged)="this.onStrengthChanged($event)" >
      </mat-password-strength>

**Comment by AnthonyNahas** [comment]
@erikknaake thanks for opening this issue! I've just patched the library and solved that!
[v3.5.2 is now live](https://www.npmjs.com/package/@angular-material-extensions/password-strength)

🍻
