### ISSUE TITLE
console.log printing out password from mat-password-strength.component.ts line 65

### ISSUE THREAD

**Issue by atgnatus** [angular-material-extensions/password-strength#151]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Windows 10

### Versions

Angular CLI: 7.3.6
Node: 10.15.0
OS: win32 x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/material                 7.3.5
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

### Repro steps

Use the mat-password-strength component, open developer javascript console, type password

### The log given by the failure

This is printed to the console:

{password: SimpleChange}
password: SimpleChange
currentValue: "MyPassword"
firstChange: false
previousValue: "MyPasswor"
__proto__: Object
__proto__: Object

### Desired functionality

console.log should be removed from mat-password-strength.component.ts line 65

**Comment by AnthonyNahas** [comment]
oh sorry! I'm gonna fix it immediately 👍 thanks for reporting

**Comment by AnthonyNahas** [comment]
I've just patched the library! 
[v3.5.3](https://www.npmjs.com/package/@angular-material-extensions/password-strengthl) is now live

cheers 🍻

**Comment by atgnatus** [comment]
Thank you.  I know I've done that before.  And thanks for the great component
