### ISSUE TITLE
Custom Regex for Validating Password and Displaying on Info Component

### ISSUE THREAD

**Issue by joechrisman** [angular-material-extensions/password-strength#155]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### OS and Version?
Windows 10

### Versions
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect             0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer  0.12.4
@angular-devkit/build-webpack   0.12.4
@angular-devkit/core                    7.2.4
@angular-devkit/schematics          7.3.0
@angular/cdk                                 7.3.6
@angular/cli                                   7.3.0
@angular/language-service           7.2.4
@angular/material                         7.3.6
@ngtools/webpack                        7.2.4
@schematics/angular                     7.3.0
@schematics/update                      0.13.0
rxjs                                                   6.4.0
typescript                                         3.1.6
webpack                                           4.28.4

### Desired functionality
Password Strength Component
- ability to set custom regex when testing password strength

Password Strength Info Component
- ability to set custom messages that correspond to the custom regex

**Comment by AnthonyNahas** [comment]
Im gonna add this Feature in the next near release 👌🍹

**Comment by AnthonyNahas** [comment]
I've just rleased [v3.7.0](https://www.npmjs.com/package/@angular-material-extensions/password-strength) which supports custom regex validation e.g: 


```html
<mat-slide-toggle #toggle>Show Password Details</mat-slide-toggle>
      
 <mat-form-field appearance="outline" style="width: 100%" [color]="passwordComponent.color">
  <mat-label>Password</mat-label>
  <mat-pass-toggle-visibility #toggleVisbility matSuffix></mat-pass-toggle-visibility>
  <input matInput #password
         [type]="toggleVisbility.type"
         placeholder="Password">
  <mat-hint align="end" aria-live="polite">
    {{password.value.length}} / {{passwordComponent.max}}
  </mat-hint>
</mat-form-field>
 
        
<mat-password-strength #passwordComponent
  (onStrengthChanged)="onStrengthChanged($event)"
  [password]="password.value"
  [customValidator]="pattern">
</mat-password-strength>

<mat-password-strength-info
  *ngIf="toggle.checked"
  [passwordComponent]="passwordComponent6"
  customCharsCriteriaMsg="1 german special chars is required"
  [enableScoreInfo]="true">
</mat-password-strength-info>

```



```ts
pattern = new RegExp(/^(?=.*?[äöüÄÖÜß])/);
```


cheers 🍻
