### ISSUE TITLE
Support @Input formControlName with <mat-password-strength>

### ISSUE THREAD

**Issue by unkn0wn-devel0per** [angular-material-extensions/password-strength#159]
- [X] feature request

### Repro steps
file.ts:
import { Validators as Special } from "@angular-material-extensions/password-strength"
let myFormGroup = formbuilder.group({
      passwdstrength:   [ '',  Special.strength( minchars, lowercases, ...etc ), Special.confirmation( fldid )],
      email:  [ '', [ Validators.required, Validators.email ]]
    });

file.html:
<mat-password-strength formControlName="passwdstrength" ...></mat-password-strength>

### Desired functionality
(Pls.) Support attribute "formControlName" for use with angular FormGroup(s)
In my special case, this would help me with:

https://material.angular.io/components/stepper/overview

<mat-step [stepControl]="myFormGroup">

(Disable transitions to next step(s) as long as form validation fails)

... would be of great help. Thanx.

Edit:
Not sure, but maybe this is the direction:
https://stackoverflow.com/questions/44731894/get-access-to-formcontrol-from-the-custom-form-component-in-angular

**Comment by AnthonyNahas** [comment]
Hi, the `formControlName ` should be attached to the `input` component and not `mat-password-strength` (see below): 


```html
<mat-form-field appearance="outline" [color]="passwordComponent.color">
            <mat-label>Password</mat-label>
            <mat-pass-toggle-visibility #toggle matSuffix></mat-pass-toggle-visibility>
            <input matInput #password
                   [type]="toggle.type"
                   required
                  [formControl]="passwordComponent.passwordFormControl" // or formControlName="what_ever_you_want"
    
                   placeholder="Password">
            <mat-hint align="end" aria-live="polite">
              {{password.value.length}} / 25
            </mat-hint>
          </mat-form-field>
```

```html
 <!--@angular-material-extensions/password-strength's main component-->
          <mat-password-strength #passwordComponent
                                 [enableDigitRule]="true"
                                 (onStrengthChanged)="onStrengthChanged($event)"
                                 [password]="password.value">
          </mat-password-strength>
```

**Comment by AnthonyNahas** [comment]
since the `mat-password-strength` should be used with an input component, the above solution will fit your requirement 🍺
