### ISSUE TITLE
Have green color as "100% strong password"

### ISSUE THREAD

**Issue by andreElrico** [angular-material-extensions/password-strength#162]
I understand the design of returning the primary color here. However my primary color is not green.
How can I make the "primary color" green? This is probably a material flaw by not having a success color.

https://github.com/angular-material-extensions/password-strength/blob/9e033f8d992470fb3396e4cfb8d0f577e0dd8b7d/src/module/component/mat-password-strength/mat-password-strength.component.ts#L85

I solved this problem by adding global styles css:

```
mat-password-strength mat-progress-bar.mat-progress-bar.mat-primary > div.mat-progress-bar-primary.mat-progress-bar-fill.mat-progress-bar-element::after {
    background-color: #155724;
}

mat-password-strength mat-progress-bar.mat-progress-bar.mat-primary > div.mat-progress-bar-secondary.mat-progress-bar-fill.mat-progress-bar-element::after {
    background-color: #155724;
}

mat-password-strength-info > mat-card  > mat-card-content > div.info-row > mat-icon.mat-icon.mat-primary {
    color: #155724;
}
```

Is there a way or any plans on making a API that styles a 100% save password green?

Something like

`@Input() savePasswordGreen: boolean`

Best wishes,
André

**Comment by AnthonyNahas** [comment]
Currently, we are only supporting the native colors of the material palette that has been selected. I can understand that a completely valid password should has a green color. I will take this feature in consideration for the next release!

Thanks for suggesting that 🍻

**Comment by AnthonyNahas** [comment]
@andreElrico could you provide please a PR to implement this feature or suggest an internal solution to override the primary color ? This would be the latest step before releasing this library in version v4

**Comment by AnthonyNahas** [comment]
@andreElrico I've just implemented this feature 🎉 

I will publish in few minutes `v3.8.0`

To use always the green color for a strong password.. just add the `green` css class to
the `mat-password-strength` like the following example: 


```html
<mat-password-strength #passwordComponent
                       class="green"
                       [password]="password.value">
</mat-password-strength>
```

Thanks again for requesting this feature, this could be interesting to integration in [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)

cheers 🍻

**Comment by AnthonyNahas** [comment]
[v3.8.0](https://www.npmjs.com/package/@angular-material-extensions/password-strength) is now live 👍

**Comment by crismani** [comment]
@AnthonyNahas This isn’t working in 4.0.1 has anything changed?

Thanks in advance for your help.

**Comment by bleuscyther** [comment]
Not working anymore

**Comment by AnthonyNahas** [comment]
I've just updated the angular and material dependencies ...

**Comment by AnthonyNahas** [comment]
I have tried to fix that.. apparently the angular material team change some css classes related to the material progress bar..

I thnik
