### ISSUE TITLE
ng add @angular-material-extensions/password-strength not getting latest release

### ISSUE THREAD

**Issue by darkedges** [angular-material-extensions/password-strength#188]
`ng add @angular-material-extensions/password-strength` gives me `3.8.0` and not `3.8.1`

Can fix manually post command so not too much of a problem, but misses some great updates.

Thanks in advance for a great tool.

**Comment by AnthonyNahas** [comment]
Did u had already the package installed ?

**Comment by adgoncal** [comment]
I had a similar issue, except it installed `3.5.0` instead. I did not have the package installed.

**Comment by AnthonyNahas** [comment]
I've just tested and patched the library to [v4.0.1](https://www.npmjs.com/package/@angular-material-extensions/password-strength) and everything is working fine 👍 

<img width="616" alt="Bildschirmfoto 2019-07-23 um 22 01 31" src="https://user-images.githubusercontent.com/20149774/61739950-250fc180-ad96-11e9-8aca-609cb04948bb.png">

![ng_add1](https://user-images.githubusercontent.com/20149774/61739970-2f31c000-ad96-11e9-8bc5-aa8ef9b7d427.gif)
![ng_add2](https://user-images.githubusercontent.com/20149774/61739971-2f31c000-ad96-11e9-9047-45cb1b79f174.gif)
![ng_add3](https://user-images.githubusercontent.com/20149774/61739972-2fca5680-ad96-11e9-966c-f92a5aa7cc8b.gif)

<img width="738" alt="Bildschirmfoto 2019-07-23 um 22 03 31" src="https://user-images.githubusercontent.com/20149774/61739983-33f67400-ad96-11e9-9ce6-3ac019fd7ae6.png">


if you are still facing any issue with that please consider to reopen this ticket #188

thank you ❤️
