### ISSUE TITLE
Place content mat-password-strength-info not working on Edge

### ISSUE THREAD

**Issue by Estevete** [angular-material-extensions/password-strength#214]
Information does not appear centered on Edge with place-content.

Chrome:
![image](https://user-images.githubusercontent.com/19273351/63249693-44512000-c26a-11e9-9d1f-b52bd74c2245.png)

Edge:
![image](https://user-images.githubusercontent.com/19273351/63249723-55019600-c26a-11e9-901c-22c1b150f385.png)

Need to override and make use of justify-content:
`mat-password-strength-info > mat-card {
  justify-content: center !important;
}`

**Comment by AnthonyNahas** [comment]
Can you provide pls a PR ?

I would appreciate that! Thank you
