### ISSUE TITLE
Confirmation Behavoire on Demo.

### ISSUE THREAD

**Issue by Syndlex** [angular-material-extensions/password-strength#229]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Linux Arch Manjaro
### Versions

On the Demo of this repo running in the web currently

### Repro steps

1. Type in Password (like: !1AaasdFf)
2. Type in Confirmation
3. Change password (by deleting f soo: !1AaasdF)
4. Input is still valid no Error is found

### Desired functionality

1. User is sure he typed in password corretlly second time.
2. Testing Currently implementing this into my app and have problems testing the Confirmation behavior. 

### Mention any other details that might be useful

I did not found any test. in the repo where the confirmation is tested.

I'm writing tests on my app and have Problems with the notConfirmed error. Should I do this in another issue?

**Comment by Syndlex** [comment]
I don't know if this is the same error but this test is also strange:
```
it('Password field and Password Confirm has to have no Confirmed Error when identically', () => {
	component.passwordComponentWithConfirmation.passwordFormControl.setValue("!1Aa");
	component.passwordComponentWithConfirmation.passwordConfirmationFormControl.setValue("!1Aa");
	component.passwordComponentWithConfirmation.passwordFormControl.updateValueAndValidity();
	fixture.detectChanges();
	fixture.whenStable().then(() => {
		expect(component.passwordValidate.errors.notConfirmed).toBeFalsy("Same Strings have an error");
	});
});
```
This Returns: 
```
Expected Object({ password: '', passwordConfirmation: '!1Aa' }) to be falsy 'Same Strings have an error'.
```


It seamse like `component.passwordComponentWithConfirmation.password` will not get set in this example. 
When running in the browser the confirmation works _except the error abouve_

**Comment by AnthonyNahas** [comment]
I think you have right! 

Do u have any suggestion to improve the confirmation feature ? A PR from you would be awesome!

**Comment by Syndlex** [comment]
So I fixed the unit tests. and the fix shows why the validation is acting like this.
The fixture needs to be updated before we type into the validation field.
I don't have any suggestion how to fix this at the moment. I am pretty new to angular.
 ```javascript
it('Password field and Password Confirm has to have not Confirmed Error when different', () => {
	component.passwordToConfirm.setValue("!1Aa");
	fixture.detectChanges();
	component.passwordValidate.setValue("!1Aa");
	fixture.detectChanges();
	fixture.whenStable().then(() => {
	    expect(component.passwordValidate.hasError("notConfirmed")).toBeFalsy("Same Strings have an error");
	});
});
```

**Comment by AnthonyNahas** [comment]
@Syndlex I will try to find some few minutes to fix that next month ;(

**Comment by LuisSama** [comment]
Has someone implemented a workaround on this? I've been looking for a solution on this matter with no Luck

**Comment by kneefer** [comment]
I'm also struggling with this...

**Comment by AnthonyNahas** [comment]
Since this ticket is now a little bit old... I will close it for now.. 

Please do not hesitate to reopen it if you are still facing the same issue with the newest version
