### ISSUE TITLE
Green Color for Success Password

### ISSUE THREAD

**Issue by crismani** [angular-material-extensions/password-strength#241]
Changing into an issue since the comment has been ignored. 

@AnthonyNahas This isn’t working in 4.0.1 has anything changed?

Thanks in advance for your help.

_Originally posted by @crismani in https://github.com/angular-material-extensions/password-strength/issues/162#issuecomment-531571720_

**Comment by AnthonyNahas** [comment]
I've just updated the angular and material dependencies ...

I will close this ticket since #162 has been now reopened
