### ISSUE TITLE
Animation on strength info component does not play

### ISSUE THREAD

**Issue by realshadow** [angular-material-extensions/password-strength#254]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Catalina

### Versions

Angular CLI: 8.3.14
Node: 12.10.0
OS: darwin x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.803.14
@angular-devkit/build-optimizer   0.803.14
@angular-devkit/build-webpack     0.803.14
@angular-devkit/core              8.3.14
@angular-devkit/schematics        8.3.14
@angular/cdk                      8.2.3
@angular/cli                      8.3.14
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.14
@schematics/angular               8.3.14
@schematics/update                0.803.14
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

### Repro steps

Minimal example with router animation - https://stackblitz.com/edit/angular-vku5es

### The log given by the failure

Enter animation (@items) in mat-strength-info component does not play when any animation is played over (before?) it. This happens when the component is used in a router outlet that has an animation or stepper component. 

### Desired functionality

Enter animation should play at all times.

### Mention any other details that might be useful

I stumbled upon this on accident and I am not even sure if thats a bug, it most likely will be a problem with my animation. Any help is appreciated

**Comment by AnthonyNahas** [comment]
it's s related to your component and the animation that ur using... 

I don't think that the router is the issue...
