### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isFirstChange' of undefined at MatPasswordStrengthComponent.ngOnChanges (password-strength.js:148)

### ISSUE THREAD

**Issue by reenezden** [angular-material-extensions/password-strength#257]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOS Catalina

### Versions
Angular CLI: 8.3.15
Node: 12.13.0
OS: darwin x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.15
@angular-devkit/build-angular     0.803.15
@angular-devkit/build-optimizer   0.803.15
@angular-devkit/build-webpack     0.803.15
@angular-devkit/core              8.3.15
@angular-devkit/schematics        8.3.15
@angular/cdk                      8.2.3
@angular/cli                      8.3.15
@angular/flex-layout              7.0.0-beta.19
@angular/material                 8.2.3
@ngtools/webpack                  8.3.15
@schematics/angular               8.3.15
@schematics/update                0.803.15
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

### Repro steps
Install via the ng add @angular-material-extensions/password-strength command.

### The log given by the failure
zone-evergreen.js:172 Uncaught TypeError: Cannot read property 'isFirstChange' of undefined
    at MatPasswordStrengthComponent.ngOnChanges (password-strength.js:148)
    at checkAndUpdateDirectiveInline (core.js:31906)
    at checkAndUpdateNodeInline (core.js:44367)
    at checkAndUpdateNode (core.js:44306)
    at debugCheckAndUpdateNode (core.js:45328)
    at debugCheckDirectivesFn (core.js:45271)
    at Object.eval [as updateDirectives] (RegisterComponent.html:194)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:45259)
    at checkAndUpdateView (core.js:44271)
    at callViewAction (core.js:44637)
### Desired functionality

I should not see the error I'm reporting

### Mention any other details that might be useful
Updating the ngOnChanges method in password-strength.js fixes the problem.  I don't like that fix though.

Orignal method:
```
ngOnChanges(changes) {
        if ((changes.externalError && changes.externalError.firstChange) || changes.password.isFirstChange()) {
            return;
        }
        else if (changes.externalError && changes.externalError.currentValue) {
            this._color = Colors.warn;
            return;
        }
        else if (changes.password.previousValue === changes.password.currentValue && !changes.password.firstChange) {
            this.calculatePasswordStrength();
        }
        else {
            this.password && this.password.length > 0 ?
                this.calculatePasswordStrength() : this.reset();
        }
    }
```

Updated/Modified method:

    ngOnChanges(changes) {
        if ((changes.externalError && changes.externalError.firstChange)) {
            return;
        }
        else if (changes.externalError && changes.externalError.currentValue) {
            this._color = Colors.warn;
            return;
        }
        // else if (changes.password.previousValue === changes.password.currentValue && !changes.password.firstChange) {
        //     this.calculatePasswordStrength();
        // }
        else {
            this.password && this.password.length > 0 ?
                this.calculatePasswordStrength() : this.reset();
        }
    }

**Comment by AnthonyNahas** [comment]
how are u using the component ?

**Comment by reenezden** [comment]
Hello @AnthonyNahas,  thanks for the quick feedback, this is how I'm using the component:

I have a client module and under impors, I imported the module like so:

MatPasswordStrengthModule.forRoot(),

Then in my register html template, I implemented it like so:
            <div class="form-row">
              <div class="form-group col-md-6">
                <mat-form-field class="full-width">
                  <input (keydown)="showPasswordDetails()" matInput #password placeholder="Password *"
                    [formControl]="registerFormGroup.get('password')" [maxlength]="10"
                    [minlength]="6" [type]="hide ? 'password' : 'text'">
                  <mat-icon matSuffix (click)="hide = !hide">{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
                  
                  <mat-error *ngIf="registerFormGroup.get('password').hasError('required')">
                    Password is <strong>required</strong>
                  </mat-error>
                  <mat-error>
                    <span *ngIf="registerFormGroup.get('password').hasError('passwordTooShort')">
                      Password is too short - min {{response.minPasswordLength}}
                    </span>
                  </mat-error>
                  <mat-hint align="end" aria-live="polite">
                    {{password.value.length}} / {{passwordComponent.max}}
                  </mat-hint>
                </mat-form-field>
              </div>
              
              <div class="form-group col-md-6">
                <mat-form-field class="full-width">
                  <input (keydown)="showPasswordDetails()" matInput #passwordConfirm placeholder="Confirm password *"
                    [errorStateMatcher]="matcher" [formControl]="registerFormGroup.get('confirmPassword')"
                    [type]="hide ? 'password' : 'text'" [maxlength]="10"
                    [minlength]="6">
                  <mat-icon matSuffix (click)="hide = !hide">{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
                  <mat-error *ngIf="registerFormGroup.get('confirmPassword').hasError('required')">
                    Confirm password is <strong>required</strong>
                  </mat-error>
                  <mat-error
                    *ngIf="registerFormGroup.controls['confirmPassword'].pristine || registerFormGroup.controls['confirmPassword'].errors?.MatchPassword">
                    Password does not match</mat-error>
                  <mat-hint align="end" aria-live="polite">
                    {{passwordConfirm.value.length}} / {{passwordComponent.max}}
                  </mat-hint>
                </mat-form-field>
              </div>
              <mat-password-strength #passwordComponent [min]="initialData?.minPasswordLength"
                [enableUpperCaseLetterRule]="initialData?.enableUpperCaseLetterRule"
                [enableLowerCaseLetterRule]="initialData?.enableLowerCaseLetterRule"
                [enableDigitRule]="initialData?.enableDigitRule"
                [enableSpecialCharRule]="initialData?.enableSpecialCharRule" [max]="initialData?.maxPasswordLength"
                (onStrengthChanged)="onStrengthChanged($event)" [password]="password.value">
              </mat-password-strength>
              <mat-password-strength-info *ngIf="enableScoreInfo"
                lowerCaseCriteriaMsg="contains at least one lower character"
                upperCaseCriteriaMsg="contains at least one upper character"
                digitsCriteriaMsg="contains at least one digit"
                specialCharsCriteriaMsg="contains at least one special character"
                minCharsCriteriaMsg="contains at least {{initialData?.minPasswordLength}} characters"
                [passwordComponent]="passwordComponent">
              </mat-password-strength-info><br /><br />
            </div>

**Comment by AnthonyNahas** [comment]
may you open a PR for that

**Comment by renu1992** [comment]
@reenezden : have u resolve this prbm...i am facing this too
