### ISSUE TITLE
Add the possibility to use svg icons in mat-password-strength-info

### ISSUE THREAD

**Issue by wutzebaer** [angular-material-extensions/password-strength#262]
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

We can't use mat-icon with the icon font from the google cdn. So we download the svg's and use them like this:

```
<mat-icon svgIcon="logout"></mat-icon>
```

It would be nice to make the mat-password-strength-info editable in some way. Or a switch to use svg icons.

**Comment by AnthonyNahas** [comment]
how are u using the info component?

**Comment by LakMoore** [comment]
+1 for me.  If you were to just add 
svgIcon="done" 
to all the positive state icons and 
svgIcon="error" 
to all the negative state icons then those users who can't or don't use Material Icons can still have an icon showing in the info panel.  

The dependency on Material Icon isn't mentioned in your list of dependencies.

**Comment by LakMoore** [comment]
![EquipMySchool_Procurement_Portal](https://user-images.githubusercontent.com/6624290/81400007-09f32000-9124-11ea-9d91-9b3d0eadfdf7.jpg)
