### ISSUE TITLE
Incompatible upgrade from v8 to v9

### ISSUE THREAD

**Issue by Sevensnake** [angular-material-extensions/password-strength#294]
Package "@angular-material-extensions/password-strength" has an incompatible peer dependency to "@angular/material" (requires "^8.2.3", would install 
"9.2.1").

Try to upgrade my application and seems like I cannot until this version is up-gradable.

**Comment by humbertojacobm** [comment]
Hello, we have the same issue, so if there is another issue where this is fixed, it would be good to know.

**Comment by AnthonyNahas** [comment]
which version was installed ? How are you updating the library ?

**Comment by AnthonyNahas** [comment]
any additional informatiom ?

I would like to close this ticket for now! 

If you are facing the same issue please consider to reopen this ticket


thank you
