### ISSUE TITLE
Mat-passwotd-strength animation not working ionic

### ISSUE THREAD

**Issue by maniya108** [angular-material-extensions/password-strength#301]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by AnthonyNahas** [comment]
actually this library is now supported for ionic! 

It has been implemented to enhance the material project for web!

**Comment by maniya108** [comment]
The progress bar animation not working properly.

**Comment by maniya108** [comment]
When am building app through angular Ivy the password-strength-info component showing error type numberInput or undefined
