### ISSUE TITLE
Can't bind to 'password' since it isn't a known property of 'mat-password-strength'

### ISSUE THREAD

**Issue by kibria06cse** [angular-material-extensions/password-strength#306]
I am trying to use password-strength. But on console I am getting this error:
"Can't bind to 'password' since it isn't a known property of 'mat-password-strength'".

What should I do?

**Comment by AnthonyNahas** [comment]
did you import the module correctly ?

**Comment by kibria06cse** [comment]
I imported on my app.module.ts. Is it necessary to import on other modules too?

**Comment by kibria06cse** [comment]
After importing on my layout module, it is working. What should I do if I want to use the confirm password feature?

**Comment by AnthonyNahas** [comment]
Can you show me your code please!

**Comment by kibria06cse** [comment]
Here is the html:
` <div class="row">
              <div class="col-sm-6">
                <mat-form-field appearance="outline">
                  <mat-label>Password</mat-label>
                  <mat-pass-toggle-visibility #toggleVisbility matSuffix></mat-pass-toggle-visibility>

                  <input matInput #passwordWithValidation [type]="toggleVisbility.type"
                    placeholder="Enter 6 digit password" formControlName="password" required>
                  <mat-error>
                    Please enter password
                  </mat-error>
                </mat-form-field>


                <mat-password-strength #passwordComponentWithValidation (onStrengthChanged)="onStrengthChanged($event)"
                  [password]="passwordWithValidation.value" class="green" [min]=6>
                </mat-password-strength>
                
                <mat-password-strength-info [passwordComponent]="passwordComponentWithValidation">
                </mat-password-strength-info>

              </div>
              <div class="col-sm-6">
                <mat-form-field appearance="outline">
                  <mat-label>Retype Password</mat-label>
                  <input matInput [type]="hideConfirmPassword ? 'password' : 'text'"
                    placeholder="Enter 6 digit password" formControlName="confirmPassword"
                    [errorStateMatcher]="matcher">
                  <button mat-icon-button matSuffix (click)="hideConfirmPassword = !hideConfirmPassword"
                    [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hideConfirmPassword">
                    <mat-icon>{{hideConfirmPassword ? 'visibility_off' : 'visibility'}}</mat-icon>
                  </button>

                  <mat-error *ngIf="registrationForm.hasError('notSamePassword')">
                    Passwords do not match
                  </mat-error>
                </mat-form-field>

                <re-captcha formControlName="recaptchaReactive"></re-captcha>

              </div>
            </div>`
