### ISSUE TITLE
Change mat-icon in mat-password-strength-info

### ISSUE THREAD

**Issue by LiorCorp** [angular-material-extensions/password-strength#309]
Feature Request
```
It's possible to change the mat-icon inside the mat-password-strength-info component ? 
```

**Comment by johnjspiteri** [comment]
@LiorCorp are you thinking of changing to another Material icon, or another library like FontAwesome?

**Comment by LiorCorp** [comment]
> @LiorCorp are you thinking of changing to another Material icon, or another library like FontAwesome?

Material icon

**Comment by AnthonyNahas** [comment]
I would appreciate a PR <3

**Comment by LiorCorp** [comment]
> I would appreciate a PR <3

Done ;)

**Comment by AnthonyNahas** [comment]
[v8.1.0](https://www.npmjs.com/package/@angular-material-extensions/password-strength) is now live
