### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Yberion** [angular-material-extensions/password-strength#397]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

Hello @AnthonyNahas, would it be possible to support Angular 16?

Have a good day.

**Comment by muraliavarma** [comment]
As a workaround if you are using `npm` package manager that you can use the `overrides` option in `package.json` to get past all the peer dependency errors - this is similar to `yarn` `resolutions`
```
  "dependencies": {
     ...
  },
  "overrides": {
    "@angular-material-extensions/password-strength": {
      "@angular/common": "^16.0.2",
      "@angular/cdk": "^16.0.1",
      "@angular/core": "^16.0.2",
      "@angular/forms": "^16.0.2",
      "@angular/material": "^16.0.1"
    }
  }
