### ISSUE TITLE
feat request: customize strength validation and info display

### ISSUE THREAD

**Issue by Drea1989** [angular-material-extensions/password-strength#68]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

Hello, thanks for sharing this, I started using it and I believe it could benefit if the password strength could be changed by parameters, for example, password length, requires special characters and so on.

this should also be reflected in the info panel where I think the final item of the password strength in percentage is redundant with the information from the bullet points and the sliding bar on top, if it could be made hidden with an optional parameter it would be great.

cheers

**Comment by AnthonyNahas** [comment]
@Drea1989 thanks for requesting the above features. I will add those changes in the next minor release. cheers 🍻
